### ISSUE TITLE
Can I use SR-IOV on the Alchemist dGPU?

### ISSUE THREAD

**Issue by daiaji** [intel/linux-intel-lts#35]
Alchemist has been released, and I think these technical details should be revealed should no longer be limited by the NDA.

**Comment by daiaji** [comment]
?

**Comment by nerfpops** [comment]
No https://www.intel.com/content/www/us/en/support/articles/000093216/graphics.html

**Comment by eero-t** [comment]
Question is answered, so I think this can be closed.

**Comment by daiaji** [comment]
Everything is beyond repair.
